ARG TARGETARCH

FROM ${TARGETARCH}/all as First

FROM nginx

ARG TARGETARCH
ENV ServerType=cpp

RUN echo $TARGETARCH
RUN mkdir -p /usr/local/server/bin/
COPY --from=First /data /usr/local/server/bin/
