# ARG TARGETARC

FROM all:${TARGETARCH} as First

FROM tarscloud/tars.cppbase

ARG TARGETARCH
ENV ServerType=cpp

RUN echo $TARGETARCH
# COPY --from=First /data/build/bin/ConfigServer /usr/local/server/bin/
