ARG TARGETARCH

FROM all:arm64 as First

FROM tarscloud/tars.cppbase

ARG TARGETARCH
ENV ServerType=cpp

RUN echo $TARGETARCH
RUN mkdir -p /usr/local/server/bin/
COPY --from=First /data /usr/local/server/bin/
